### 1. 물품 등록
POST localhost:8080/v1/admin/product
Content-Type: application/json

{
  "productName": "바나나",
  "price": 1000,
  "stock": 200
}


### 2. 물건 조회
GET localhost:8080/v1/products/search?name=


### 3. 포인트 충전
POST localhost:8080/v1/points/1/charge
Content-Type: application/json

{
  "balance": 1000000
}

### 4. 물건 구매
POST localhost:8080/v1/orders
Content-Type: application/json

{
  "userId": 1,
  "orderItems": [
    {
      "productId": 1,
      "quantity": 10
    },
    {
      "productId": 2,
      "quantity": 5
    }
  ],
  "shippingAddress": "서울시"
}